const buttonClass = " px-6 flex-row items-center justify-center " as const;
const buttonTextClass = " font-semibold text-base " as const;

export const cls = {
  bg: {
    base: "bg-bg-light dark:bg-bg-dark",
    pure: "bg-white dark:bg-black",
    pureAlt: "bg-black dark:bg-white",
    grey100: "bg-[#F8F8F8] dark:bg-[#222]",
    grey150: "bg-[#F5F5F5] dark:bg-[#242424]",
    grey200: "bg-[#EDEDF3] dark:bg-[#303030]",
    grey300: "bg-gray-300 dark:bg-gray-800",
    opacified05: "bg-black/5 dark:bg-white/5",
    opacified10: "bg-black/10 dark:bg-white/10",
    opacified20: "bg-black/20 dark:bg-white/20",
    opacified30: "bg-black/30 dark:bg-white/30",
    opacified40: "bg-black/40 dark:bg-white/40",
    opacified50: "bg-black/50 dark:bg-white/50",
    opacified60: "bg-black/60 dark:bg-white/60",
    opacified70: "bg-black/70 dark:bg-white/70",
    opacified80: "bg-black/80 dark:bg-white/80",
    opacified90: "bg-black/90 dark:bg-white/90",
    opacifiedAlt05: "bg-white/5 dark:bg-black/5 ",
    opacifiedAlt10: "bg-white/10 dark:bg-black/10 ",
    opacifiedAlt20: "bg-white/20 dark:bg-black/20 ",
    opacifiedAlt30: "bg-white/30 dark:bg-black/30 ",
    opacifiedAlt40: "bg-white/40 dark:bg-black/40 ",
    opacifiedAlt50: "bg-white/50 dark:bg-black/50 ",
    opacifiedAlt60: "bg-white/60 dark:bg-black/60 ",
    opacifiedAlt70: "bg-white/70 dark:bg-black/70 ",
    opacifiedAlt80: "bg-white/80 dark:bg-black/80 ",
    opacifiedAlt90: "bg-white/90 dark:bg-black/90 ",
    danger: "bg-red-400 dark:bg-red-800",
    primary: "bg-primary dark:bg-primary",
    primaryLight: "bg-primary-light dark:bg-primary-light",
    accentGreen: "bg-[#07B53B]",
    accentRed: "bg-[#E50F0F]",
  },
  text: {
    pure: "text-black dark:text-white",
    pureAlt: "text-white dark:text-black",
    base: "text-black/90 dark:text-white/90",
    shade100: "text-black/80 dark:text-white/80",
    shade200: "text-black/70 dark:text-white/70",
    shade300: "text-black/60 dark:text-white/60",
    shade400: "text-black/50 dark:text-white/50",
    primary: "text-primary",
    primaryVariable: "text-primary dark:text-primary-light",
    accentGreen: "text-[#07B53B]",
    accentRed: "text-[#E50F0F]",
  },
  border: {
    class: "border-gray-300 dark:border-gray-700",
    class05: "border-gray-300/50 dark:border-gray-700/50",
  },
  btn: {
    buttonClass,
    buttonTextClass,
    primary: `${buttonClass} bg-primary py-3.5 rounded-4xl`,
    flat: `${buttonClass} bg-transparent py-3.5 rounded-4xl`,
    primaryText: `${buttonTextClass} text-white`,
    danger: `${buttonClass} bg-red-700 dark:bg-red-300 py-2.5 rounded-4xl`,
    dangerText: `${buttonTextClass} text-white dark:text-red-800`,
    bg: `${buttonClass} bg-primary-dark dark:bg-white py-2.5 rounded-4xl`,
    bgText: `${buttonTextClass} dark:text-black text-white`,
  },
  input: {
    className:
      "px-4 py-4 rounded-xl bg-gray-100 dark:bg-white/10 text-slate-800 dark:text-slate-200 font-normal",
    borderClassName: "border border-neutral-300 dark:border-neutral-800",
    underline:
      "border-b border-black/40 dark:border-white/40 text-gray-800 dark:text-gray-100",
  },
} as const;
