export const placeholders = {
  genres: [
    "action",
    "adult",
    "adventure",
    "animation",
    "biography",
    "comedy",
    "crime",
    "dance",
    "documentary",
    "drama",
    "family",
    "fantasy",
    "horror",
    "kids",
    "legal",
    "mystery",
    "reality-tv",
    "romance",
    "sci-fi",
    "thriller",
    "war",
    "western",
  ],

  languages: [
    "albanian",
    "arabic",
    "bengali",
    "chinese",
    "czech",
    "dutch",
    "filipino",
    "finnish",
    "french",
    "german",
    "hindi",
    "hungarian",
    "indian",
    "indonesian",
    "italian",
    "japanese",
    "korean",
    "malay",
    "mandarin",
    "nigerian",
    "persian",
    "polish",
    "punjabi",
    "romania",
    "russian",
    "spanish",
    "tagalog",
    "tamil",
    "telugu",
    "thai",
    "turkish",
    "vietnamese",
  ],

  greetings: [
    "We hope you're loving the experience",
    "What do you want to watch today?",
    "You can favourite movies to watch them later",
    "I don't know your name, but I know what you're here for",
    "Popcorn ready? Let's find your next favorite!",
    "Lights, camera, action! What's on your watchlist?",
    "Your cinematic journey starts here.",
    "Ready for a plot twist? Explore our collection!",
    "Escape reality, one movie at a time.",
    "Grab a blanket, it's movie time!",
    "Feeling adventurous? Discover something new!",
    "Your personal movie concierge is here.",
    "From blockbusters to hidden gems, we've got you covered.",
    "Let's make some movie magic!",
  ],
};
