// Generated by rn-genicons

/* eslint-disable @typescript-eslint/no-explicit-any, @typescript-eslint/no-unused-vars */

import success_check from "../../assets/images/colored-icons/success_check.svg";

import React, { forwardRef } from "react";
import { SvgProps } from "react-native-svg";

import { useResolveClassNames } from "uniwind";

/**
 * Props for AppSvg
 *
 * - `icon`: SVG component (from react-native-svg transformer)
 * - `className`: Tailwind classes (will be ignored if a supported style is not used)
 * - All standard SvgProps are supported
 */
export interface AppSvgProps extends SvgProps {
  icon: React.ComponentType<SvgProps>;
  className?: string;
}

/**
 * AppSvg
 *
 * A thin wrapper around SVG icons that:
 * - Accepts Tailwind `className`
 * - Forwards all SvgProps
 * - Supports refs
 *
 * Designed for shared icon packages.
 */
export const AppSvg = forwardRef<any, AppSvgProps>(
  ({ icon: Icon, className = "", ...svgProps }, ref) => {
    const styles: any = useResolveClassNames(className);
    const styleProps: any = { ...styles, style: [svgProps.style, styles] };

    return <Icon ref={ref} {...svgProps} {...styleProps} />;
  },
);

AppSvg.displayName = "AppSvg";

export const AppColoredIcons = {
  success_check: (props: Omit<AppSvgProps, "icon">) => (
    <AppSvg icon={success_check} {...props} />
  ),
};
