// Generated by rn-genicons

/* eslint-disable @typescript-eslint/no-explicit-any, @typescript-eslint/no-unused-vars */

import at from "../../assets/images/flat-icons/at.svg";
import avatar_fill from "../../assets/images/flat-icons/avatar_fill.svg";
import avatar_outline from "../../assets/images/flat-icons/avatar_outline.svg";
import business_outline from "../../assets/images/flat-icons/business_outline.svg";
import card_fill from "../../assets/images/flat-icons/card_fill.svg";
import card_outline from "../../assets/images/flat-icons/card_outline.svg";
import chevron_down from "../../assets/images/flat-icons/chevron_down.svg";
import document_outline from "../../assets/images/flat-icons/document_outline.svg";
import fingerprint from "../../assets/images/flat-icons/fingerprint.svg";
import home_fill from "../../assets/images/flat-icons/home_fill.svg";
import home_outline from "../../assets/images/flat-icons/home_outline.svg";
import lock_outline from "../../assets/images/flat-icons/lock_outline.svg";
import phone_fill from "../../assets/images/flat-icons/phone_fill.svg";
import questionmark_circle from "../../assets/images/flat-icons/questionmark_circle.svg";
import spinner from "../../assets/images/flat-icons/spinner.svg";
import transaction_history_fill from "../../assets/images/flat-icons/transaction_history_fill.svg";
import transaction_history_outline from "../../assets/images/flat-icons/transaction_history_outline.svg";

import React, { forwardRef } from "react";
import { SvgProps } from "react-native-svg";

import { useResolveClassNames } from "uniwind";

/**
 * Props for AppSvg
 *
 * - `icon`: SVG component (from react-native-svg transformer)
 * - `className`: Tailwind classes (will be ignored if a supported style is not used)
 * - All standard SvgProps are supported
 */
export interface AppSvgProps extends SvgProps {
  icon: React.ComponentType<SvgProps>;
  className?: string;
}

/**
 * AppSvg
 *
 * A thin wrapper around SVG icons that:
 * - Accepts Tailwind `className`
 * - Forwards all SvgProps
 * - Supports refs
 *
 * Designed for shared icon packages.
 */
export const AppSvg = forwardRef<any, AppSvgProps>(
  ({ icon: Icon, className = "", ...svgProps }, ref) => {
    const styles: any = useResolveClassNames(className);
    const styleProps: any = { ...styles, style: [svgProps.style, styles] };

    return <Icon ref={ref} {...svgProps} {...styleProps} />;
  },
);

AppSvg.displayName = "AppSvg";

export const AppIcons = {
  at: (props: Omit<AppSvgProps, "icon">) => <AppSvg icon={at} {...props} />,
  avatar_fill: (props: Omit<AppSvgProps, "icon">) => (
    <AppSvg icon={avatar_fill} {...props} />
  ),
  avatar_outline: (props: Omit<AppSvgProps, "icon">) => (
    <AppSvg icon={avatar_outline} {...props} />
  ),
  business_outline: (props: Omit<AppSvgProps, "icon">) => (
    <AppSvg icon={business_outline} {...props} />
  ),
  card_fill: (props: Omit<AppSvgProps, "icon">) => (
    <AppSvg icon={card_fill} {...props} />
  ),
  card_outline: (props: Omit<AppSvgProps, "icon">) => (
    <AppSvg icon={card_outline} {...props} />
  ),
  chevron_down: (props: Omit<AppSvgProps, "icon">) => (
    <AppSvg icon={chevron_down} {...props} />
  ),
  document_outline: (props: Omit<AppSvgProps, "icon">) => (
    <AppSvg icon={document_outline} {...props} />
  ),
  fingerprint: (props: Omit<AppSvgProps, "icon">) => (
    <AppSvg icon={fingerprint} {...props} />
  ),
  home_fill: (props: Omit<AppSvgProps, "icon">) => (
    <AppSvg icon={home_fill} {...props} />
  ),
  home_outline: (props: Omit<AppSvgProps, "icon">) => (
    <AppSvg icon={home_outline} {...props} />
  ),
  lock_outline: (props: Omit<AppSvgProps, "icon">) => (
    <AppSvg icon={lock_outline} {...props} />
  ),
  phone_fill: (props: Omit<AppSvgProps, "icon">) => (
    <AppSvg icon={phone_fill} {...props} />
  ),
  questionmark_circle: (props: Omit<AppSvgProps, "icon">) => (
    <AppSvg icon={questionmark_circle} {...props} />
  ),
  spinner: (props: Omit<AppSvgProps, "icon">) => (
    <AppSvg icon={spinner} {...props} />
  ),
  transaction_history_fill: (props: Omit<AppSvgProps, "icon">) => (
    <AppSvg icon={transaction_history_fill} {...props} />
  ),
  transaction_history_outline: (props: Omit<AppSvgProps, "icon">) => (
    <AppSvg icon={transaction_history_outline} {...props} />
  ),
};
